### ISSUE TITLE
is the local-cov operation position-specific?

### ISSUE THREAD

**Issue by phoebe1996511** [hjSim/NTIRE2019_deblur#1]
is the local-cov operation position-specific? Assuming that the result's shape is (4,256,256,25,3),the kernel_2d is (4,256,256,25,1)，the three channels corresponding to each pixel share kernel_2d's 5×5  parameters?

**Comment by hjSim** [comment]
Yes. Three channels are RGB channels in a pixel, and the 5x5 parameters of kernel_2d are applied to each R,G and B channel respectively in the same way (three times) .
